// client/src/pages/LoginPage.tsx
import { createSignal } from "solid-js";
import { useNavigate } from "@solidjs/router";
import api from "../lib/axios";

export default function LoginPage() {
  const [email, setEmail] = createSignal("");
  const [password, setPassword] = createSignal("");
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const res = await api.post("/member/login", {
        email: email(),
        password: password(),
      });
      alert("로그인에 성공했어요.");
      navigate("/profile");
    } catch (err) {
      alert(err.response?.data?.message || "로그인 실패");
    }
  };

  return (
    <form onSubmit={handleLogin} class="auth-container">
      <h2>로그인</h2>
      <div class="form-group">
        <input 
          type="email" 
          class="form-control"
          placeholder="이메일" 
          onInput={(e) => setEmail(e.currentTarget.value)} 
        />
      </div>
      <div class="form-group">
        <input
          type="password"
          class="form-control"
          placeholder="비밀번호"
          onInput={(e) => setPassword(e.currentTarget.value)}
        />
      </div>
      <button type="submit" class="btn btn-primary" style={{ width: "100%" }}>로그인</button>
    </form>
  );
}

// client/src/views/LoginPage.vue
<template>
  <div class="page-container">
    <header class="page-header">
      <h1>로그인</h1>
    </header>

    <section class="page-body">
      <form @submit.prevent="onSubmit" class="auth-form">
        <label>
          이메일
          <input v-model="email" type="email" required />
        </label>
        <label>
          비밀번호
          <input v-model="password" type="password" required />
        </label>
        <div class="actions">
          <button type="submit" class="btn btn-primary">로그인</button>
          <router-link to="/signup" class="btn btn-link">회원가입</router-link>
        </div>
        <p v-if="error" class="error">{{ error }}</p>
      </form>
    </section>
  </div>
</template>

<script>
import api from '../lib/axios'
import { useRouter } from 'vue-router'
import { useAppStore } from '../stores/appStore'

export default {
  name: 'LoginPage',
  data(){
    return { email: '', password: '', error: '' }
  },
  setup(){
    const router = useRouter()
    const app = useAppStore()
    return { router, app }
  },
  methods: {
    async onSubmit(){
      this.error = ''
      try{
        const res = await api.post('/member/login', { email: this.email, password: this.password })
        if(res.data && res.data.success){
          const user = res.data.data
          this.app.setCurrentUser(user)
          this.router.push('/')
        }else{
          this.error = res.data?.message || '로그인에 실패했습니다.'
        }
      }catch(e){
        this.error = e.response?.data?.message || e.message || '서버 에러'
      }
    }
  }
}
</script>

<style scoped>
.page-container{padding:12px}
.auth-form{display:flex;flex-direction:column;gap:8px;max-width:360px}
.auth-form label{display:flex;flex-direction:column}
.actions{display:flex;gap:8px;align-items:center;margin-top:8px}
.error{color:#c00;margin-top:8px}
</style>
